language: php

php:
  - 7
  - 5.6
  - 5.5

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.3

addons:
  code_climate:
    repo_token: 82c0aac3de3676696ac8f1018e7c223f8f891ea3
    
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar self-update
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - mkdir -p build/cov
  - phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
  - vendor/bin/test-reporter